### PR TITLE
Added Gigabyte to manufacturer code, and added gitignore file.

### PR DESCRIPTION
**Pull request by ujjukumar**
1) Added Gigabyte to manufacturer code
2) Added gitignore file
3) Modified Readme file to include link for Contribution page.

### CODE REVIEW

**Comment by Crozzers** [comment]
Would it be alright to trim the `.gitignore` file down a bit? There's a lot of stuff in there with little relevance to this project.
Just looking through, here are some sections I think aren't likely to be needed:
* `C extensions`
* `PyInstaller`  though to `SageMath parsed files`
* `Spyder project settings` through to `mkdocs documentation`
* And everything after the static type checker sections

**Comment by ujjukumar** [comment]
Thanks for suggestion, I have removed extra items from gitignore.

**Comment by Crozzers** [comment]
Cool, thank you! I'll get this merged and released this weekend

**Comment by Crozzers** [comment]
`v0.19.0` has been released with the changes. Thank you for your contribution!

**Pull request merged**
